<?php
ini_set("include_path", "../lib/Mnix".PATH_SEPARATOR."../../../lib/Mnix".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'Core.php';

/**
 * Test class for Mnix_Core.
 * Generated by PHPUnit on 2009-08-25 at 20:33:34.
 */
class Mnix_CoreTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Mnix_Core
     * @access protected
     */
    protected $object;

    protected function setUp()
    {
        //$this->object = new Mnix_Core;
    }

    /*protected function tearDown()
    {
        $this->object = null;
    }*/

    public function testTTT()
    {
        var_dump($this->object);
        $this->assertEquals(1, 1);
    }
}
